// src/utils/generateReceipt.js
export async function generateReceipt({
  donorWallet,
  donorName,
  campaignTitle,
  amountSol,
  amountLabel,
  txSignature,
  transactionLabel,
  campaignId,
  paymentMethod = "solana",
  referenceId,
}) {
  const { jsPDF } = await import("jspdf");

  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const date = new Date().toLocaleString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    timeZone: "Asia/Kathmandu",
  });

  const signatureValue = txSignature || referenceId || "Not available";
  const finalAmountLabel =
    amountLabel ||
    (amountSol !== undefined && amountSol !== null
      ? `${parseFloat(amountSol || 0).toFixed(6)} SOL`
      : "Amount unavailable");
  const finalTransactionLabel = transactionLabel || (paymentMethod === "esewa" ? "Solana Reference" : "Transaction Signature");
  const explorerUrl = txSignature
    ? `https://explorer.solana.com/tx/${txSignature}?cluster=devnet`
    : "Solana explorer link not available";
  const receiptNum = `NDR-${Date.now().toString().slice(-8)}`;
  const W = 210;

  doc.setFillColor(15, 17, 23);
  doc.rect(0, 0, W, 297, "F");

  doc.setFillColor(192, 57, 43);
  doc.rect(0, 0, W, 3, "F");

  doc.setFillColor(30, 32, 40);
  doc.roundedRect(20, 12, W - 40, 30, 4, 4, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("NepalDaan", 30, 30);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(192, 57, 43);
  doc.text("Blockchain Charity Donation Platform", 30, 37);
  doc.setTextColor(120, 120, 140);
  doc.text("Powered by Solana Blockchain | Devnet", W - 30, 30, { align: "right" });

  doc.setFillColor(192, 57, 43);
  doc.roundedRect(20, 52, W - 40, 18, 3, 3, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("DONATION RECEIPT", W / 2, 63, { align: "center" });

  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 120, 140);
  doc.text(`Receipt No: ${receiptNum}`, W - 25, 76, { align: "right" });

  let y = 82;
  const addField = (label, value, highlight = false) => {
    doc.setFillColor(30, 32, 40);
    doc.roundedRect(20, y, W - 40, 16, 2, 2, "F");
    doc.setTextColor(120, 120, 140);
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.text(label.toUpperCase(), 27, y + 6);
    doc.setTextColor(highlight ? 230 : 220, highlight ? 126 : 220, highlight ? 34 : 235);
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    const textValue = String(value || "Not available");
    const trimmed = textValue.length > 60 ? `${textValue.slice(0, 58)}...` : textValue;
    doc.text(trimmed, 27, y + 13);
    y += 20;
  };

  addField("Campaign", campaignTitle || `Campaign #${campaignId || "N/A"}`);
  addField("Donation Amount", finalAmountLabel, true);
  addField("Payment Method", paymentMethod === "esewa" ? "eSewa + Solana verification" : "Phantom + Solana transfer");
  addField("Donor", donorName || donorWallet || "Unknown donor");
  addField("Date & Time (Nepal Time)", date);
  addField(finalTransactionLabel, signatureValue);

  if (referenceId && referenceId !== txSignature) {
    addField("eSewa Reference ID", referenceId);
  }

  y += 4;

  doc.setFillColor(20, 22, 30);
  doc.roundedRect(20, y, W - 40, 22, 3, 3, "F");
  doc.setFillColor(192, 57, 43);
  doc.roundedRect(20, y, 3, 22, 1.5, 1.5, "F");
  doc.setTextColor(120, 120, 140);
  doc.setFontSize(8);
  doc.text("VERIFY ON SOLANA EXPLORER", 28, y + 7);
  doc.setTextColor(59, 158, 255);
  doc.setFontSize(8);
  const explorerText = explorerUrl.length > 72 ? `${explorerUrl.slice(0, 72)}...` : explorerUrl;
  doc.text(explorerText, 28, y + 14);
  y += 32;

  doc.setDrawColor(39, 174, 96);
  doc.setLineWidth(0.5);
  doc.roundedRect(20, y, W - 40, 16, 3, 3, "D");
  doc.setTextColor(46, 204, 113);
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text("VERIFIED ON SOLANA BLOCKCHAIN | IMMUTABLE RECORD", W / 2, y + 10, { align: "center" });
  y += 26;

  doc.setDrawColor(40, 42, 50);
  doc.setLineWidth(0.3);
  doc.line(20, y, W - 20, y);
  y += 8;
  doc.setTextColor(70, 70, 85);
  doc.setFontSize(7.5);
  doc.setFont("helvetica", "normal");
  doc.text("This receipt is automatically generated by NepalDaan Blockchain Charity Donation System.", W / 2, y, {
    align: "center",
  });
  doc.text("The recorded Solana transaction can be independently verified on Solana Explorer.", W / 2, y + 5, {
    align: "center",
  });

  const filename = `NepalDaan-Receipt-${receiptNum}.pdf`;
  doc.save(filename);
  return filename;
}
